### ISSUE TITLE
undname.exe returns Code -1

### ISSUE THREAD

**Issue by rootCBR** [mavenlin/wrap_dll#9]
The script doesn't work. I'm not familiar enough with Python to fix it, but I have narrowed the cause down to `subprocess.check_output([args.undname, f.name])`.

**Comment by leegggg** [comment]
There is some bug with `tempfile`. For now I just change the line `with tempfile.NamedTemporaryFile(mode='w+t') as f:` to `with open("tempdata",mode='w+t') as f:` as a workaround.

**Comment by mavenlin** [comment]
The original program seems to run okay when I tested it.
Thanks @leegggg for figuring this out, do you mind opening a pull request on the fix?
Instead of using "tempdata", we may use `os.path.join(tempfile.gettempdir(), os.urandom(24).hex())` to generate a random file name, and delete it once it is done.

**Comment by CRC32EX** [comment]
This script not working.
Same error on my environment.

No response for over 2 weeks already passed.
I'm noob for Python.
Please fix @mavenlin.

**Comment by mavenlin** [comment]
fixed in b9762f3bdf6bd7532937edfd5ec501444938f3cd

**Comment by CRC32EX** [comment]
This issue was already resolved.
Please close this issue.
